global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hww'
    scrape_interval: 10s
    metrics_path: /varz
    static_configs:
      - targets: ['hww:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
