apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    owner: zhemer
  name: grafana
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app: grafana
    owner: zhemer
status:
  loadBalancer: {}
