apiVersion: v1
kind: Service
metadata:
  labels:
    app: hww
    owner: zhemer
  name: hww
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: hww
status:
  loadBalancer: {}
