apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hww
  name: hww
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hww
    spec:
      containers:
      - name: hww
        image: hww
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/healthz
          failureThreshold: 3
          periodSeconds: 15
          timeoutSeconds: 10
        name: hww
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
