apiVersion: v1
kind: ConfigMap
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'hww'
        scrape_interval: 10s
        metrics_path: /varz
        static_configs:
          - targets: ['hww:8080']

      - job_name: 'prometheus'
        scrape_interval: 10s
        static_configs:
          - targets: ['localhost:9090']
metadata:
  name: cm-prom
  labels:
    app: prometheus
    owner: zhemer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    owner: zhemer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        owner: zhemer
    spec:
      containers:
      - args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --storage.tsdb.retention.time=200h
        - --storage.tsdb.retention.size=200MB
        - --web.enable-lifecycle
        image: prom/prometheus:v2.10.0
        name: prometheus
        ports:
        - containerPort: 9090
        resources: {}
        volumeMounts:
          - name: vm-cm-prom
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml

          - name: vm-prom-data
            mountPath: /prometheus

      restartPolicy: Always
      volumes:
        - name: vm-cm-prom
          configMap:
            name: cm-prom

        - name: vm-prom-data
          persistentVolumeClaim:
              claimName: prometheus-pvc

status: {}
